<?php
if (isset($_SESSION["user"])){// I need: joining groups, exiting groups, making groups

?>
<div>
    <form method="POST">
        <button name="createGroup">create group</button>
    </form>
</div>
<?php
if (isset($_SESSION["user"])){
    ?>
<h2>your groups</h2>
<div class="groups">
<?php
foreach($joined as $group){
    ?>
<div class="group">
    <div class="groupInfo">
        <p class="groupName"><?=$group["tagName"]?></p>
        <p><?=$group["tagDesc"]?></p>
    </div>
    
    <?php
if (isset($_SESSION["user"])){
    ?>
    <div class="groupButton">
        <?php
    //joining and leaving groups
    if ($group["userId"]!==$_SESSION["user"]["userId"]){
        ?>
    <form method="POST">
        <input type="hidden" name="tagId" value="<?=$group["tagId"]?>">
        <button name="joinGroup" class="joinButton">Join</button>
    </form>
    <?php
    }
    else{
        ?>
        <form method="POST">
            <input type="hidden" name="tagId" value="<?=$group["tagId"]?>">
            <button name="leaveGroup" class="leaveButton">leave</button>
        </form>
        <?php
    }
    ?>
    </div>
    <?php
}
?>
</div>
<?php
}
}
?>
</div>
<p>not done yet ;-; how has it taken me so long?</p>
<!-- add group listing where userName is !-->
<!-- I probably won't need to change userNames in connections, since it already is only connected to the user, just gonna have to change it in the tags!-->

<h2>groups</h2>
<?php
}
?>
<div class="groups">
<?php
foreach($list as $group){
    ?>
<div class="group">
    <div class="groupInfo">
        <p class="groupName"><?=$group["tagName"]?></p>
        <p><?=$group["tagDesc"]?></p>
    </div>
    
    <?php
if (isset($_SESSION["user"])){
    ?>
    <div class="groupButton">
        <?php
    //joining and leaving groups
    $switch=true;
    foreach($joined as $gop){
        if ($gop["tagId"]===$group["tagId"])$switch=false;
    }

    if ($switch===true){
        ?>
    <form method="POST">
        <input type="hidden" name="tagId" value="<?=$group["tagId"]?>">
        <button name="joinGroup" class="joinButton">Join</button>
    </form>
    <?php
    }
    ?>
    </div>
    <?php
}
?>
</div>
<?php
}
?>
</div>