
<form method="POST" enctype="multipart/form-data" autocomplete="off" style="padding:24px">
    <fieldset style="padding:24px">
        <legend>comment</legend>
    <div>
        <label for="commText"> text <br></label>
        <!--<input style="width:200px; height:300px;" type="text" name="commText" id="commText"> !-->
        <textarea name="commText" id="commText" style="min-height:100px; min-width:500px; max-width: 500px; max-height:100px"></textarea>
    </div>
    <div>
        <label for="commFile"> files/images </label>
        <input type="file" name="commFile" id="commFile">
    </div>

    <button name="finishComm" autocomplete="off">finish</button>

    </fieldset>
</form>