 <style>
     #userImage{
         width: 100px;
         height:100px;
         border-radius: 2%;
         border-color: black;
         border-style: solid;
         border-width:1px;
        }
</style>
<div>
    <form method="POST">
        <button name="closeComm">X</button>
    </form>
</div>

   <div class="thing">

        <?php


if ((int)$thing["userType"]===1){
    ?>
     <style>
         <?="#user".$thing["userId"]?>{
            color: lightskyblue;
            font-weight: bold;
        }
     </style>
    <?php
 }
 ?>
<div class="thingStuff">
        <div> <!-- top of thing!-->
            <div class="thingUserStuff">
                <h2 id="<?="user".$thing["userId"]?>"><?=$thing["userName"]?></h2>
                <img src="<?=$thing["userImage"]?>" alt="<?=$thing["userName"]?>" id="userImage">
            </div>
            <div class="thingAgeStuff">
                <p><?= date("g:i:s d.m.Y" ,strtotime($thing["thingAge"]))?></p>
            </div>
        </div>
        <div class="thingFileStuff">
            <p style="white-space: pre-wrap;"><?=$thing["thingText"]?></p>
            <?php
        if ($thing["thingFile"]===null);
        else if ($thing["FileIsWhat"]==="image"){
            ?>
                <img id="some" src="<?=$thing["thingFile"]?>" width="auto" height="auto">
                <?php
        }
        else {
            ?>
            <a href="<?=$thing["thingFile"]?>"><?=substr($thing["thingFile"], 10)?></a>
            <?php
        }
        ?>


        </div>
        <div class="thingTagDiv">
            <?php
            $tagIds = explode(",", $thing["tagIds"]);
            $tagNames =explode(",", $thing["tagNames"]);//turns names into arrs 
            $tagDescs=explode(",", $thing["tagDescs"]);
            $tagTypes=explode(",", $thing["tagTypes"]);
            //now connect each tagId with each tagName
            $tags = [];
            for ($i=0;$i<count($tagIds);$i++){
                $tags[$i]["tagId"]=$tagIds[$i];//for future use :)
                $tags[$i]["tagName"]=$tagNames[$i];
                $tags[$i]["tagDesc"]=$tagDescs[$i];
                $tags[$i]["tagType"]=$tagTypes[$i];//for checking if a tag is a USER or THING or GROUP type (different stylizations) ... this is going to be such a pain for the tags created before I added tagTypes to thing Creation
            };
            foreach ($tags as $tag){
                if (($tag["tagId"])){//checks if there are tags (the statement returns null if there are no tags)
                    ?>
                <div class="thingTagStuff">
                    <p><?=$tag["tagName"]?></p>
                    <p><?=$tag["tagDesc"]?></p>
                    <p><?=$tag["tagType"]?></p>
                </div>
                <?php
                }
            }
            ?>
        </div>


        <?php
        if(isset($_SESSION["user"]))
        if ($_SESSION["user"]["userId"]===(int)$thing["userId"]||$_SESSION["user"]["userType"]!==null){//people with userType that isn't null will be able to change everything
            ?>
            <div class="thingChangeStuff">
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" value="<?=$thing["thingId"]?>"name="editId">
                    <input type="hidden" value="<?=$thing["thingText"]?>"name="editText">
                    <input type="hidden" value="<?=$thing["thingFile"]?>"name="editFile">
                    <input type="hidden" value="<?=$thing["FileIsWhat"]?>"name="editType">
                    <button name="remove">remove</button>
                    
                    <?php
                    if ($_SESSION["user"]["userId"]===(int)$thing["userId"]){
                    //ONLY USERS CAN EDIT THEIR OWN STUFF, I DON'T WANT TO PUT STUFF INTO OTHER PEOPLES MOUTHS
                    ?>
                        <button name="edit">edit</button>
                    <?php
                    }
                    ?>
                </form>
            </div>
                <?php
        
        echo "<br>";
        //var_dump($thing);
        ?>
        <!-- a field of small tags, which extends when prompted(button), only a bit is shown beforehand !-->
</div>
</div><!-- for whole post!-->

<form method="POST" enctype="multipart/form-data" autocomplete="off" style="padding:24px">
    <fieldset style="padding:24px">
        <legend>comment</legend>
        <form method="GET">
            <input type="hidden" value="<?=$_GET["showComms"]?>" name="showComms">
        </form>
        <div>
            <label for="commText"> text <br></label>
            <!--<input style="width:200px; height:300px;" type="text" name="commText" id="commText"> !-->
            <textarea name="commText" id="commText" rows="10" cols="100"></textarea>
        </div>
        <div>
            <label for="commFile"> files/images </label>
            <input type="file" name="commFile" id="commFile">
        </div>
        
        <button name="addComm" autocomplete="off">finish</button>
        
    </fieldset>
</form>
<?php
}

//needs 2 requests, 1 for thing, other for comm (I'm not dealing with more array complications)
//thing
//---------
//create comm
foreach ($thingComms as $coom){
    var_dump($coom);
?>   
<p><?=$coom["userId"]?></p>
<p><?=$coom["comAge"]?></p>

<p style="white-space:pre-wrap"><?=$coom["comText"]?></p>

<!--need img differentiation here!!-->
<?php
if($coom["comFile"]!==null)
if ($coom["fileType"]==="image"){
    ?>
    <img src="<?=$coom["comFile"]?>">
    <?php
}
else{
?>
    <a href="<?=$coom["thingFile"]?>"><?=substr($thing["thingFile"], 10)?></a>
<?php
}
//don't forget edit and delete if owner ;D
?>

 <?php
}
?>