
<form method="POST" enctype="multipart/form-data" autocomplete="off" style="padding:24px">
    <fieldset style="padding:24px">
        <legend>edit</legend>
    <div>
        <label for="thingText"> text <br></label>
        <!--<input style="width:200px; height:300px;" type="text" name="thingText" id="thingText"> !-->
        <textarea name="thingTextNew" id="thingTextNew" style="min-height:100px; min-width:500px; max-width: 500px; max-height:100px"><?=$GLOBALS["editText"]?></textarea>
    </div>
    <div>
        <label for="thingFile"> files/images </label>
        <input type="file" name="thingFileNew" id="thingFileNew">
    </div>
    
    <?php
    if ($GLOBALS["editFile"]===null);
        if ($GLOBALS["editType"]==="image"){
            ?>
                <img id="some" src="<?=$GLOBALS["editFile"]?>" width="auto" height="auto">
            <?php
        }
        else {
            ?>
                <a href="<?=$GLOBALS["editFile"]?>"><?=substr($GLOBALS["editFile"], 10)?></a>
            <?php
        }
        $tagValue="";
        foreach($tags as $tag){
            if ($tag["tagType"]==="THING") $tagValue=$tagValue.$tag["tagName"]." ";
        }
        ?>
        <div>
            <label for="thingTagNew">tags</label>
            <input type="text" value="<?=$tagValue?>" name="thingTagNew" id="thingTagNew">
        </div>
        <?php
    var_dump($GLOBALS["editFile"]);
    var_dump($GLOBALS["editType"]);
    var_dump($GLOBALS["editText"]);
    var_dump($GLOBALS["editId"]);
    ?>
    <br>
    <input type="hidden" value="<?=$GLOBALS["editId"]?>" name="IdChange" id="IdChange">
    <button name="somethingEdit" autocomplete="off">finish</button>

    </fieldset>
</form>