
<?php //button for creating things when logged in
if (isset($_SESSION["user"])){
?>
<form method="post">
    <button name="create">create</button>
</form>
<?php
}
?>


<div class="things">
    <?php
foreach ($things as $thing){
    ?>
<div class="thing">
        <?php
if ((int)$thing["userType"]===1){
    ?>
     <style>
         <?="#user".$thing["userId"]?>{
            color: lightskyblue;
            font-weight: bold;
        }
     </style>
    <?php
 }
 ?>
    <div class="thingStuff">
        <div>
            <div class="topOfThing"> <!-- top of thing!-->
                <div class="thingUserStuff">
                    <img src="<?=$thing["userImage"]?>" alt="<?=$thing["userName"]?>" id="userImage">
                </div>
                <div class="thingTextStuff">
                    <div class="thingInfo">
                        <h2 id="<?="user".$thing["userId"]?>"><?=$thing["userName"]?></h2>
                        <p><?= date("g:i:s d.m.Y" ,strtotime($thing["thingAge"]))?></p>
                    </div>
                    <p style="white-space: pre-wrap;"><?=$thing["thingText"]?></p>
                </div>
            </div>
        </div>
        <div class="thingFileStuff">
                <?php
        if ($thing["thingFile"]===null);
        else if ($thing["FileIsWhat"]==="image"){
            ?>
                <img id="some" src="<?=$thing["thingFile"]?>" width="auto" height="auto">
                <?php
        }
        else {
            ?>
            <a href="<?=$thing["thingFile"]?>"><?=substr($thing["thingFile"], 10)?></a>
            <?php
        }
        ?>


        </div>
        <div class="thingTagDiv">
            <?php
            $tagIds = explode(",", $thing["tagIds"]);
            $tagNames =explode(",", $thing["tagNames"]);//turns names into arrs 
            $tagDescs=explode(",", $thing["tagDescs"]);
            $tagTypes=explode(",", $thing["tagTypes"]);
            //now connect each tagId with each tagName
            $tags = [];
            for ($i=0;$i<count($tagIds);$i++){
                $tags[$i]["tagId"]=$tagIds[$i];//for future use :)
                $tags[$i]["tagName"]=$tagNames[$i];
                $tags[$i]["tagDesc"]=$tagDescs[$i];
                $tags[$i]["tagType"]=$tagTypes[$i];//for checking if a tag is a USER or THING or GROUP type (different stylizations) ... this is going to be such a pain for the tags created before I added tagTypes to thing Creation
            };
            foreach ($tags as $tag){
                if (($tag["tagId"])){//checks if there are tags (the statement returns null if there are no tags)
                    ?>
                <div class="<?="tag".$tag["tagType"]?> thingTagStuff <?="tag".$tag["tagName"]?>">
                    <p class="tagName"><?=$tag["tagName"]?></p>
                    <p class="tagDesc" id="<?="tagDesc".$tag["tagDesc"]?> tagDesc"><?=$tag["tagDesc"]?></p>
                </div>
                <?php
                    //gather all unique tags on current page
                    $switch = false;
                    foreach ($tagList as $tagLester){
                        if ($tagLester["tagName"]===$tag["tagName"]) $switch=true; 
                    }
                    if ($switch===true) $switch=false;
                    else array_push($tagList, $tag);
                }
            }
            ?>
        </div>


        <?php
        if(isset($_SESSION["user"]))
        if ($_SESSION["user"]["userId"]===(int)$thing["userId"]||$_SESSION["user"]["userType"]!==null){//people with userType that isn't null will be able to change everything
            ?>
            <div class="thingChangeStuff">
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" value="<?=$thing["thingId"]?>"name="editId">
                    <input type="hidden" value="<?=$thing["thingText"]?>"name="editText">
                    <input type="hidden" value="<?=$thing["thingFile"]?>"name="editFile">
                    <input type="hidden" value="<?=$thing["FileIsWhat"]?>"name="editType">
                    <button name="remove">remove</button>
                    
                    <?php
                    if ($_SESSION["user"]["userId"]===(int)$thing["userId"]){
                    //ONLY USERS CAN EDIT THEIR OWN STUFF, I DON'T WANT TO PUT STUFF INTO OTHER PEOPLES MOUTHS
                    ?>
                        <button name="edit">edit</button>
                    <?php
                    }
                    ?>
                </form>
            </div>
                <?php
        }
        echo "<br>";
        //var_dump($thing);
        ?>
        <!-- a field of small tags, which extends when prompted(button), only a bit is shown beforehand !-->
    </div><!-- 
    divides comment from other thing...
    feature for comments to rollout.........NEEDS JS
    !-->
    <div id="comms">
        <form method="GET">
            <input type="hidden" name = "pageNum"value="<?=$_GET["pageNum"]?>">
            <button id="showComms" name="showComms" value="<?=$thing["thingId"]?>">comments</button>
        </form>
    </div>
</div><!-- for whole post!-->

<?php
}
?>
</div>
