
<form method="POST" enctype="multipart/form-data" autocomplete="off" style="padding:24px">
    <fieldset style="padding:24px">
        <legend>creation</legend>
    <div>
        <label for="thingText"> text <br></label>
        <!--<input style="width:200px; height:300px;" type="text" name="thingText" id="thingText"> !-->
        <textarea name="thingText" id="thingText" style="min-height:100px; min-width:500px; max-width: 500px; max-height:100px"></textarea>
    </div>
    <div>
        <label for="thingFile"> files/images </label>
        <input type="file" name="thingFile" id="thingFile">
    </div>
    <div>
        <label for="thingTags"> tags </label>
        <input type="text" name="thingTags" id="thingTags">
        <p>
            tags are divided by " ", if no tags found, they are made
        </p>
    </div>
    <button name="finish" autocomplete="off">finish</button>

    </fieldset>
</form>