<?php
if (!isset($_GET["pageNum"])) $_GET["pageNum"]=0;
?>
<form method="GET" name="pages" id="pages">
    <div class="pageSelect">
        <a class="back"><</a>
        <input type="hidden" value="<?=$_GET["searchStr"]?>" name="searchStr" id="searchStr">
        <input type="number" value="<?=$_GET["pageNum"]?>" id="pageNumber" name="pageNum" max="<?=$maxPage?>" min="0">
        <a class="forth">></a>
    </div>
</form>
<?php

//I could load a value into input, and change it with js?
//idk I am confused

// I think I will just hide the pageNum input and add js to change its values
?>
