
<h5>tags are created when they don't exist during thing creation, so it is useless to put it here</h5>
<h5>you can also use TEXT: to search for text content of things</h5>
<div class="allTags">
    <div class="thingTags">
        <h3>THING tags</h3>
        <?php
    foreach($thingTags as $tag){
        ?>
    <div class="thingTag">
        <p><?=$tag["tagName"]?></p>
        <p><?=$tag["tagDesc"]?></p>
        <p><?=$tag["tagCount"]?></p>
    </div>   
    <?php
    }
    ?>
</div>
<div class="UserTags">
    <h3>USER tags</h3>
    <?php
    foreach($userTags as $tag){
        ?>
    <div class="userTag">
        <p><?=$tag["tagName"]?></p>
        <p><?=$tag["tagDesc"]?></p>
        <p><?=$tag["tagCount"]?></p>
    </div>   
    <?php
    }
    ?>
</div>
<div class="groupTags">
    <h3>GROUP tags</h3>
    <?php
    foreach($groupTags as $tag){
        ?>
    <div class="groupTag">
        <p><?=$tag["tagName"]?></p>
        <p><?=$tag["tagDesc"]?></p>
        <p><?=$tag["tagCount"]?></p>
    </div>   
    <?php
    }
    ?>
</div>
</div>