<?php
$first =!isset($_cookie["first"]);
if ($first){
    setcookie("first", "true");
}
if (isset($_SESSION["user"])){
    var_dump($_SESSION["user"]);
}

?>




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="some.css">
    <title>Document</title>
</head>
<body>
    <nav>
        <div class="navLeft">

            <div>
                <a href="/somethingig/something.php">something</a>
            </div>
            <div>
                <a href="/somethingig/documentation.php">documentation</a>
            </div>
            <div>
                <a href="/somethingig/thingTags.php">Tags</a>
            </div>
            <div>
                <a href="/somethingig/groups.php">groups</a>
            </div>
        </div>
        <div class="navRight">

            <?php
        if (!isset($_SESSION["user"])){
            ?>
        <div>
            <a href="/somethingig/register.php">register</a>
        </div>
        <div>
            <a href="/somethingig/login.php">login</a>
        </div>
        <?php
        }
        else{
            ?>
        <div>
            <?php
            if ($_SESSION["user"]["userType"]===1){
                ?>
                <style>
                    #userName{
                        color:lightskyblue;
                        text-decoration: ;
                        font-weight: bold;
                    }
                    </style>
                <?php
            }
            ?>
            <div>
                <a id="userName" href="/somethingig/profile.php"><?=$_SESSION["user"]["userName"]?></a>
            </div>
        </div>
            
        </div>    
        <?php
        }
        ?>


    </nav>