<fieldset>
    <legend>name</legend>
    <form method="POST">
        <div>
            <label for="name">name</label>
            <input type="text" id="name" name="name">
        </div>
    <button name="changeName">name</button>    
</form>
</fieldset>
    
<fieldset>
<legend>password</legend>
<form method="POST">
        
        
    <div>
        <label for="pass">current password</label>
        <input type="password" id="pass" name="pass" >
    </div>
    <div>
        <label for="newPass">new password</label>
        <input type="password" id="newPass" name="newPass">
    </div>
    <div>
        <label for="newPassCheck">password check</label>
        <input type="password" id="newPassCheck" name="newPassCheck">
    </div>
    <button name="changePass">password</button>
</form>
</fieldset>
<fieldset>
    <legend>description</legend>

<form method="POST">
    <div>
        <label for="desc">description</label>
        <input type="text" id="desc" name="desc" >
    </div>
    
    
    <button name="changeDesc">description</button>
    
</form>
</fieldset>