<h2>register</h2>

<form method="POST" enctype="multipart/form-data">
    <div>
        <label for="name">name</label>
        <input type="text" id="name" name="name" required>
    </div>

    <div>
        <label for="pass">password</label>
        <input type="password" id="pass" name="pass" required>
    </div>
    <div>
        <label for="passCheck">password check</label>
        <input type="password" id="passCheck" name="passCheck" required>
    </div>
    <div>
        <label for="image">profile image</label>
        <input type="file" name="image" id="image" accept="image/*">
    </div>

    <button name="register">register</button>

</form>